#+Title:一份关于大流行的反思
* 引言
当谈论到大流行，大多数人的印象是：病毒造成了全球医疗系统的瘫痪，经济、秩序都受到了巨大冲击。无论在医疗上，还是在经济上，人们被迫度过了不安全的两年。随着疫苗的推出和病毒的弱化，大流行已经接近尾声。大流行造成的世界秩序的混乱，经济的衰退和停滞，才是当下需要面对的。
然而，爆料革命的情报为我们勾画出大流行的全貌。大流行不仅仅是人类社会的一次偶然的灾难，它至少应该包含中共制造病毒、全球疫情和疫苗灾难。参加爆料革命我成功逃过了疫苗，并且在感染时有解药。我与大多数了解真相的人一样，认为大流行是少数邪恶之人对全人类犯下的可怕罪行，他们既借全球精英之手屠杀无辜的公众，又利用精英的。整个世界分化成为疯狂的刽子手和无助的受害者，还有一部分尽力挽救受害者的人，虽然我们大多数时候无能为力。谋杀者之所以谋杀是因为他们疯狂、邪恶，或者被疯狂、邪恶的思想蛊惑。受害者被杀害是因为他们没有能力与强大的敌人抗衡。其他人只能看着这一切发生，迷茫而痛苦，因为他们知道只有爆料革命的胜利，将中共消灭才能结束这场人间浩劫。
但当我，我才开始意识到，我的思路错了。


爆料革命已经将有关大流行的真相公之于众，


随着疫苗灾难和一系列次生灾难（如经济危机）的陆续爆发，以及灭共进程的推进，越来越多人会苏醒。理解大流行就显得格外重要。在不久地未来，青蒿类药物或许可以最大程度的拯救多数人的性命，但如果随着大流行灾难的解决，我们对它的关注也就此结束，那么最终结果就是，痛苦从我们对大流行的记忆中逐渐消退，大流行传递给我们的信息也就没有听众，也无人传播。我试图以一系列文章为一项被忽视却具有思想重要性的任务做出一些贡献。这个任务就是对大流行进行结构性反思，并使反思所得进入当代社会的自我认知、制度实践和社会成员之中。
（不明真相的公众视角）
对于如今尚不明真相的公众，他们已经开始觉得大流行尾声将至。即使作为爆料革命参与者，我仍然。连支持大流行真相的群体也几乎只有爆料革命，那对此展开反思的就更不可能超出爆料革命群体。然而，事实上，类似的反思也并不多见。
（一系列错误的处理，如研究分流、公众意识清洁，最终导致大流行的刺痛从记忆中拔出）

当我们被问到：这一系列的事件是如何发生在如此文明的现代？如何理解现代文明下的这一系列灾难？如何理解这些灾难在文明进程中的地位？我们的内心可能不会有太多波澜。\\

我们几乎不会把大屠杀与光鲜亮丽的现代文明相连，不会认为它在昭示现代文明的一个深层的危机，而是将其看作一系列特殊事件，或者是一类广泛常见的社会现象的极端情况，我们必须容忍它，因为它具有回复性和普遍性，现代社会过去、现在和将来都是一个被设计来压制它甚至消灭它的组织。
* 现代文明与疫苗灾难
** 如何理解现代文明下的疫苗灾难？
贬低、误解或者轻视大流行的倾向：将大流行、疫苗灾难(全人类大屠杀)视作文明化进程的失败，不可能是人类文明化进程的产物。这种角度将造成一个结果：大流行被视为一个“特殊”事件，对它的反思也就止步于事情层面，无法对文明的人性进行深入的反思。

事实上，大流行过程中的每一个因素（在现代人看来）都是正常的，完全符合现代文明的原则、精神、世界观、价值观。现代的官僚制度、理性精神、高效原则、科学主义（思维）、赋予主观世界以价值等理论，不包含任何可以防止此类暴行的可能性的机制，也没有任何东西能够将此类行为定义成暴行。现代文明当然不是大流行的充分条件，但无疑是必要条件。没有现代文明，疫苗灾难是不可想象的。正是由于现代文明的工具理性精神，已经将它制度化的官僚体系形式，才使得疫苗灾难成为可能，并且使它的执行方案格外合理。
** 现代官僚体制存在什么问题？它和大流行有什么关系？
现代官僚制度是疫苗屠杀得以设计、实施和实现的重要机制。作为使工具理性制度化的官僚系统，它使得大屠杀的解决方案成为可能，并增加了这一方案贯彻实施的可能性。层制将社会视为被控制、掌握、改进与重塑的对象，以理性化、科学化、专业化的运作原则使得大屠杀远远超过了过去的屠杀事件。
层级化和功能的劳动分工是现代官僚体系的核心特征，其后果是成员以技术的责任代替了道德的责任。劳动分工使对集体性和组织性行动的成果有所贡献的大多数人，与该成果本身之间产生距离。

精细的劳动功能划分使成员在实践和认知上都与最终的效果发生距离，意味着官僚体系中的绝大多数人可能在没有了解其指令的结果的情况下发出命令，或者不假思索地奉命行事。他们对自己的指令或行为的后果只有抽象、孤立的认识。
细致的功能划分和任务分离，将导致身处体质内的个体用技术责任代替道德责任。两者的区别在于，技术责任忘记了行动是达成行动本身以外的目的的手段。只求把行动本身做好。

官僚体系行为对象的非人化
用纯粹技术性、道德中立的方式来表述这些对象。非人化开始于官僚机构行为所针对的对象因距离而可以并实际上被简化为一套定量措施时。在疫苗屠杀中，对于卫生官员而言，对他们的工作对象有意义的说明就是公众的疫苗接种率。
当官僚体系执行任务的对象被有效地非人化，并因此被抛弃作为道德需求的潜在对象，他们就会被带着道德冷漠的眼光看待。一旦他们的抵抗或不配合阻碍了官僚程序的顺畅，这种道德冷漠就会很快转变为非难和指责。官僚体系甚至会采取某种强制性的手段以保证官僚程序的流畅。
** 执行者
执行者的行为
行为的中介是现代社会最显著和最基本的一个特征，与高度分工非常密切。意图和实际执行之间存在很大的距离，两者之间的空间里充满栋梁的细微行为和不相干的行动者。中介阻挡了行动者的目光，让他看部件行为的结果。行为与结果的距离增加超过了道德自抑发挥作用的程度。
人类残酷的倾向与受害者的接近程度负相关。行为的中介使得多数成员远离受害者，因而更加专注与行为而非良心。

服从理论
在序列化的行动中，行动者成为自己过去行动的奴隶，这种控制远超其他制约。如果否定某次行动的正当性，那么上次行动也是正当的？因此没什么比分担在行动者看来是犯罪行为的责任更能把他们联系在一起，所以同谋者通常比较团结，而且会”一条路走到黑‘“。
官僚体系中的道德被赋予了新的含义，如忠诚、服从、尽责、义务、纪律等概念，以适配现代化的官僚体系。于是上级成了道德关怀的最高目标，同时又是最高的道德权威。忠诚即在纪律规范下尽个人义务。
复杂多层级的官僚体系将导致责任的推卸。这意味着责任的湮灭，意味着原本的道德权威不起作用。
** 受害者的合作
疫苗屠杀过程中，权威机构利用受害者的理性进行压制，从而使得屠杀的过程得以更低的成本进行。封锁受害者+拯救你所能拯救者。
(病毒和疫苗灾难是如何发生的？政府、技术官僚机构的信用和权威，以及民众对权威的迷信；迷信权威的原因有，公众丧失了批判性思维，无法通过独立思考分辨真相；权威通过广义的教育手段，对公众进行洗脑，既让公众失去批判性思维，又不断传递虚假信息）
（考察大流行从最具代表性的现象，如公众对疫苗的态度、精英对疫苗的态度、技术官僚的行为，还原灾难发生的过程，揭示权威的堕落与公众的麻木。结论：在权威的堕落和公众的麻木中，灾难就这样发生了。）

（当论及病毒和疫苗灾难，指的是大面积感染、死亡、后遗症、副作用。病毒和疫苗不仅带来了急性的感染，还对健康有着持久的损害。以至于健康的精子卵子都成了稀缺资源，人类的平均寿命可能都有所下降。除了健康上的短期、长期影响，大流行还加剧全球经济压力，造成大面积失业，倒闭，无数人失去了经济来源，艰难度日。）
** 既是执行者/施害者又是被害者
** 无意识社会与意识的注入（产生）
*** 精英主义
*** 园艺文化/医疗文化（（高层精英的）社会意识）
现代性可以理解为“理性化”，我称之为理性的工具化。自启蒙运动，理性和科学成为新的神话和宗教。现代社会以对自然和自身的积极管理态度著称。科学活动不是为了科学而科学；首要的，它应该充当一个力量强大的工具，以允许工具持有者改善现状，根据人类的计划和设计改造现实，并帮助推动这个工具达到自我完善。如今启蒙理性变成了工具理性。

现代性的原则：理性化，我称之为理性的工具化。现代性的雄心：高效。现代性的“工具”：科学（主义）。现代性的直接结果：高度分工的社会组织形式。
高度分工的结果：极度依赖社会秩序；依赖社会精英（权威）；人的工具化倾向；良知的失效和道德的重构。
当良知失效，平庸之恶发作的时候，基于社会秩序形成的整个社会体制就进入了“盲目”状态，可以将任何美善的扭曲成为邪恶的，只需要向它注入动机。
而这个动机就是最高的精英为了维持秩序，就需要将所有对秩序稳定有威胁的因素都消除。比如，当老年人口多而养老金已经告竭时，消灭老年人就是一个最有效的选择。

现代性表现为对秩序的一种永无止境的构建。知识和权力的共生是现代性最显著的特征。
理性作为认识真理的基础，逐渐被运用于除了神学、哲学和科学以外领域，使它从认识真理的启蒙理性，逐渐沦为构建秩序的工具理性。
科学主义是一种思想，指科学是世界最权威的世界观，也是人类最重要的知识，其高于所有一切其他东西对生活的诠释。这一信念使自然科学的研究和其所采用的方法终于上升到了意识形态的水平。

1. 受科学革命影响，人们试图运用科学及理性的角度，去建立政治或社会制度的通则。
2. 虽然启蒙哲学家各别观点不同，但一致相信人类理性的有效性，并支持社会、经济及政治的改革。
3. 科学革命的冲击，造成启蒙运动与工业革命的出现，影响了欧洲与人类的社会。
** ？
与现代性的认知框架关注秩序和混乱、正常与反常、中心与边缘的二元划分不同，后现代性所关注的恰恰是这种二元划分中不断扩大的”“灰色地带”。从“灰色地区”出发，后现代性寻求进行创造并将自身永远陷入不稳定的更新状态的原动力（对帕森斯的系统秩序理论的反叛，用游戏术语来说，帕属于守序善良，而鲍则属于混乱中立）。
* 批判性反思现代文明与人性缺口
难道现代文明是退步吗？是现代文明导致了灾难的发生吗？

【当平庸之恶遇上现代性：理性和良知的丧失】
启蒙理性压缩为工具理性。
公众为什么会合作？
（体制化就是一个理性和良知逐渐丧失的过程，其根源在于人性中的平庸之恶。平庸之恶扮演了类似罪的角色，它是导致人类不能持守理性和良知的根源。）
（平庸之恶是一种不假思索，它体现出人类对真理和美善的轻视；体制化是缓慢发生的，不容易察觉，也很难不发生在人身上。如果不对此怀有警惕，就更容易却更大程度被体制化。）
（人为什么会体制化、被世界塑形？因为人类需要寻找存在的意义？）

显然，现代文明的许多思想、理念和成果都是非常好的，因为人类的天性是向往美善的。但这种对美善的向往和感知并不能很好地保持，当良知受挑战时，它的发挥可能遇到困难。当对美善的追求愈发热烈时，人就可能抛弃良知的声音。这也并非人所愿意的，否则也不会将现代文明带来的各种可能阻碍良知发挥作用的因素称为挑战和困难。换言之，并非现代性导致人性堕落，而是人向往美善的天性既美好又脆弱，人类没有太多保持纯真的心智和能力。现代性无疑是诱发或促进了人性败坏的发生，但真正的根源在于人性之中有着一个与生俱来的缺口。（这个缺口就会让我们在不知不觉中丢失对美善最纯真的向往，因而在愿意为善的时候，恶的种子就已经埋下。）


** 大流行的根源：现代性、体制化与平庸之恶
（病毒和疫苗灾难为什么会发生？病毒疫苗灾难是现代性体制化+平庸之恶[不假思索]的必然结果。平庸之恶是卷入体制、逐渐丧失批判性思维的根源，即人类拥有理性[对真理的感知和向往]和良知[对善的感知和向往]却没有持受理性和良知的能力[工具理性可能会保留]。它是人类的理性和良知在面对现代性时表现得无比脆弱的根源[之一]。）
（病毒灾难的发生，有基本条件，如权威作恶、公众迷信。权威建立、巩固到作恶，与公众批判性思维、独立思考能力的丧失一路相随。不可否认，权威利用了自己的优势，迫使公众进一步放弃独立思考能力，但公众同样为此负责，因为自己的平庸之恶。我想说，病毒灾难的发生并不是文明进程的插曲，它是自然的结果。并非权威者单方面伤害公众，而是体制化的权威和公众共同完成的一次“大屠杀”）
（现代性体制扮演了什么角色（类似律法）？人类对秩序有需要，以至于对权威有需求。现代性的原则导致社会过度分工，许多人将自己工具化，并依赖其他不同的工具人。最终，将独立思考、独立判断的“工作”都分工给了各个领域的权威。批判性思维&独立思考判断“能力”的缺失，导致公众对权威产生了不可“戒断”的精神依赖。各个领域的各级权威都follow更大的权威，最终几乎所有人都依赖各个领域中的极少数人做出的判断/断言。然后，这极少数人就将人类拉入深渊。）

* 原罪论
【原罪：一切败坏的根源】
（人的内心总是向往美善，但这种向往在面对现代性的原则时显得异常脆弱，最终人就被现代文化塑形。人有良心，向往良心所指向的美善，却不具备持守良心的能力。这种面对世界无法持守良心，以至于逐渐麻木、堕落的人性根源，可以部分概括为平庸之恶。）
（澄清原罪论不是性恶论，它强调不是人类的本性是邪恶的，而是人虽然有良心，有对美善的感知和向往，却不能持守，最终使美善败坏而无能为力。可以再进行某些补充说明，如原罪论对启蒙思想的影响，以及对美国建立的影响，以让原罪论更好接受。）
（讨论原罪论的真理性，主要的论证就是人类文明发展过程中，各种恶行发生的必然性。如，大屠杀必然发生。美国的腐败也是必然的。中共的统治也是必然的。病毒和疫苗灾难也是必然的。）
（人如何面对原罪？事情上只能通过各种方式提高人类作恶的成本，并不断地纠正错误，以延缓美善败坏的过程。而且必须始终警醒，任何纠错只能让人类短暂地回归“正轨”，依靠人类的力量不可能彻底解决原罪。根源上原罪只能通过人性的更新消解，所以只能诉诸信仰。）
* 现代文明的革命
事情层面能做的就是变革。理清问题和挑战，给出解决原则、思路或方案。必须强调不能过分的追求完美的秩序（现代性就是对秩序的一种永无止境的构建）。

延续前文提到的问题。

去中心化革命（铸币权、组织/协作）

AI技术对现代文明分工秩序的冲击
应用AI的出现可能对人的工具化倾向带来巨大挑战

病毒、疫苗灾难的长远后果

【教育维度】
教育能做的其实也不多，独立人格和批判性思维是很难通过某种设计而培养的。从科学主义的角度出发进行设计，最终可能重蹈覆辙。但教育的首要原则就是，尽力使人的良知可以最大程度保留并发挥作用。教育同时非常重要，唯有教育能够让输入社会体制中的成员最大程度地保留良知和启蒙理性。



【秩序的重建】【信用危机】【爆料革命】
（如何重建秩序？人类如何重新回到适度的分工协作之中？）
（讨论具体事情层面如何应对后病毒疫苗时代的信用崩塌、秩序崩塌等问题。就信用、秩序重建，以及对现代的纠错给出解决思路。讨论在此过程中爆料革命的使命--以真相刺破时代的“泡沫”，保留人类重建文明的力量，并成为文明重建的中流砥柱）
（爆料革命既是现代文明的最大革命者，揭示真相，消灭CCP这个现代文明的最大产物，为信用危机提供解决方案等）
（爆料革命与历史上的革命不同，不是从思想革命中爆发）
（爆料革命对灭共后的文明重建，包括思想、秩序、体制、教育等，其实并没有太多的构思，但这并没有问题，只是需要对此有所讨论。）
* 人性的救赎

【灾难之审判：谁为病毒和疫苗灾难负责？每一个人。】
（没有律法何来审判？人的理性和良知就是律法。？？？是否要写这个话题？？？）

为什么讨论人性的救赎？我们的人性有缺口，如果缺口无法被填补，无论新秩序设计得多么完善，终究没有解决根本问题。而且，当我们面对现代文明某种程度的瓦解（比如AI挑战了人类的存在的价值），以及人性存在缺口的真相时，人的价值和意义是什么？人的归属在哪里？无数的问题浮出水面。
作为一个现代人，我们把自己当成社会分工的一员，但事实上这只是人的社会角色。许多人将社会角色就当作了自己，然而，难道没有社会角色的人就没有存在的意义了吗？就不是人了吗？在现代文明秩序尚且稳定的时期，人们可能不太关注这个问题。然而，当AI的出现，许多人面临着失去社会角色的威胁，将自己工具化的倾向遭到挑战。难道失去社会角色的人就失去了意义了吗？人真正的意义、价值和本质是什么？面对这些问题，哲学只能部分地回答，却不能提供终极的答案。
能解决人性的诸多疑问的，唯有宗教信仰。
但在面临人性存在缺口的真相时，几乎所有宗教都显得格外无力。先验直觉告诉我们，任何残缺的，不完美的事物，不可能拥有永恒的价值和意义。换言之，任何哲学回答最终都会面临一个无法解决的问题：人有没有永恒的价值、意义和归宿？若有，人性不应该有缺口。若没有，难道我们所追求一切都没有永恒的价值吗？我们就存在于永恒的无意义（虚空）之中。
真正的信仰应该具有以下原则：
1. 承认人性不完美的事实。
2. 提供人性更新的救赎。
