* 现代性主题要哪些思考和写作的方向？
如果文明进程是向着启示录而去，那么思考和写作的重心就应该放在揭示真相，预言文明进程和人性的救赎上。揭示真相不为了世界向着我所期望的方向进行，而是服务于信仰。
** 揭示现代性的危机
大流行作为现代性的验证，揭示了现代人对现代性有崇拜。我们认为现代社会是构建来防范大流行等灾难发生的组织，事实上它是令大流行得以设计、实施并最终成功的必要条件。（现代官僚制度、现代的观念...）

现代社会的组织方式（尤其是现代官僚制度）是设计和实施大流行的重要环节。现代社会的组织方式如何影响社会成员，让大流行成为现实？

现代的观念是形成、维持现代组织运行的精神内核，它对现代社会中的每个成员的影响都以现代社会的组织为载体。（精英主义、工具理性主义、科学主义）
现代观念（现代性的原则）孕育了现代性的危机。现代观念的不良结果。将人异化为工具、符号、数据。平庸的个人与“盲目”的社会。对秩序、工具的永无止境的构建和追求。
现代观念崇尚工具理性而压制了其他天赋能力，尤其是良心。行动皆诉诸工具理性，而非良心。所谓现代观念，本质上就是一种？？结构，它决定现代人为何以及如何运用良心、理性、审美等天赋能力。（信仰缺席、人本主义的价值观念）

现代防卫的失效（现代性危机）及其意义。现代性提供一种确定性的来源（也是行为的原则），即工具理性，失效是因为工具理性虽然具备一定的有效性，却并不具有完备性。这让我们有机会重新审视我们所崇尚的现代观念（理性原则...）。
** 理解现代观念
现代性危机根植于现代的观念（危机与观念的共生关系），理解现代观念是探索危机解决方案或者预测文明进程的必经之路。

现代有哪些核心观念？它们有哪些特点，是怎么在文明进程中形成的？可以追溯到哪些神学、哲学思想，或者政治、经济、文化、科学、技术、军事上的观念？
理性、科学、效率、经验、秩序；工具化、理性化、专业化、权威化、全球化；无神论、唯物论、人本主义、精英主义；
1. 科学的工具化：科学活动无法自我维持，需要依靠科研基金的支持。科研工作者进行着科学活动，很可能是认为自己在求知求真，或者造福社会、国家甚至人类。但事实上，科学活动的方向是由资助者操控的，他们将科学塑造成宗教，并利用来引导、蒙蔽甚至控制公众的认知和思想。在资助者眼中，科学的另一个作用，就是作为服务于技术发展的支持探索活动，是用来发展技术，以提高人类力量的一环。所以，即使作为科研工作者仍然以探索未知的自然真理为动力，但科学活动宏观上的目的已经彻底工具化。
2. 理性的工具化：

如何面对这些观念，抛弃、修正还是加固？
（当我们还运用理性反思，继续走构建的路线，就仍然处于现代。）
** 文明进程走向何方？
文明的进程不取决于个人的思想。真相揭开的程度、公众反思的深度，将决定具体哪些观念被抛弃、哪些被修正、哪些被加固。瓦解现代性的力量和修正、加固现代性的力量之间的张力平衡点，就决定了文明的走向。

有哪些影响文明走向的因素？
大流行、疫苗灾难。
爆料革命、灭共。
铸币权的非国家化。
AI与区块链的繁荣。
...

大流行、疫苗灾难是否会引发政府和医疗技术官僚的信用危机？
铸币权的非国家化会产生什么影响？
...

下个时代会发生什么，变成什么样子？是否仍在现代的范畴内？
为了应对疫苗灾难而解除医学伦理禁忌，开放精子卵子拍卖、干细胞技术等。

怎么理解启示录对文明进程的预言？
** 讨论原罪
** （次要）如何修正现代的观念和现代社会的组织方式？
