* 前言(d)
  :PROPERTIES:
  :UNNUMBERED: 1
  :END:
第一章（现代性与大流行）试图还原大流行的发生机制和过程，揭示现代性与大流行的内在联系，即现代性使大流行的设计和执行成为可能。\\
第二章（现代性的深层危机）将讨论大流行揭露的现代性深层危机，即现代社会无力防止大流行发生，又妨碍良知发挥防范大流行的作用。这个危机的根源，是现代性对工具理性的过度信任和使用，以至于压制甚至扭曲了良知功能。不可否认，工具理性在许多领域非常有效，但超出工具理性范畴地使用工具理性（工具理性过度扩张）将挤压良知的空间。这种对良知的压制会导致良知在那些需要发挥作用的时候失效。无独有偶，工具理性同样挤压了人先验的美学感知的空间，现代人的审美是被工具理性（科学）所设计的。这本质上是现代性的结构危机，工具理性的过度扩张，导致其他人类的天赋能力受到挤压，无法发挥功能的同时，还逐渐畸形。而这种畸形成为一种现代社会的传统，不断地影响着所有现代人，塑造者他们的自我认知。这种塑形将导致现代社会在过度释放工具理性而压制其他天赋人性的路上越走越远。越多天赋人性的丧失，将导致人类在那些领域越发无能，越发依赖工具理性。而大流行就是在这种工具理性的滥用中诞生的。\\
第三章（脆弱的良知）将从大流行的普遍性，以及现代性的深层危机出发，揭示一个隐藏于人性之中的深层危机，即人拥有感知和向往美善的良知，但人的行为却总是导致良知所不接受的罪行。大流行既具有普遍性，有具有特殊性。它的特殊性源于现代性，而普遍性体现在类似结构的罪行并非现代性的独特产物，而是人类历史始终伴随的韵脚。这种普遍性提醒我们，罪行的根源不在于现代性，而在于始终伴随人类的魔咒。尽可能收缩工具理性的空间，让良知可以发挥功能，在一定程度上能够解决现代性的危机，但它的结构危机却并非完全来源于我们错误或者偏差的认知。它本质上来源于我们良知的一个结构危机。如果我们斥责工具理性过度扩张，就必须承认良知的脆弱。当良知与工具理性产生张力时，通常是良知会作出让步。虽然良知具有判断善恶的能力，但它总不能规范人的行为。我们承认我们总能分辨并且向往美善，当我们发现我们总不能得到美善的结果。\\
第四章（后现代社会理论初探），试图。现代社会几乎会随着中共的灭亡和疫苗灾难的解决而落幕，后中共、后疫苗时代几乎等同于后现代。后现代性将从现代性的二元结构中超越，寻求失序和构建之间寻找一种动态的过程。它与现代性追求构建一个静态完美的社会的乌托邦式理想主义不同，是一种寻求理性收缩、良知回归的，不过度构建的模式。同时古典复兴、与宗教信仰的回归也是一个趋势，理性将从工具理性重新成为认识真理的理性。人类必须面对的是工具理性的失败，它不能压制，也不能医治人类良知的底层危机（常面困境又常失效）。在人类的诸多天赋能力中，理性和良知都无法医治人性的原罪，既然人类无法向内寻求自我医治，那么就必须向外寻求拯救。这并没有问题，应为如果这个结构性的危机或者困难根源于人性中的不足或者漏洞，那么自然无法自我完善解决。
* 良知、大流行与现代性
分析大流行如何从现代社会孕育而出。
** 良知之压制
执行者难道没有良知吗？如果他们意识到自己可能在作恶，还会执行吗？
执行者的行为
行为的中介是现代社会最显著和最基本的一个特征，与高度分工非常密切。意图和实际执行之间存在很大的距离，两者之间的空间里充满栋梁的细微行为和不相干的行动者。中介阻挡了行动者的目光，让他看部件行为的结果。行为与结果的距离增加超过了道德自抑发挥作用的程度。
人类残酷的倾向与受害者的接近程度负相关。行为的中介使得多数成员远离受害者，因而更加专注与行为而非良心。

服从理论
在序列化的行动中，行动者成为自己过去行动的奴隶，这种控制远超其他制约。如果否定某次行动的正当性，那么上次行动也是正当的？因此没什么比分担在行动者看来是犯罪行为的责任更能把他们联系在一起，所以同谋者通常比较团结，而且会”一条路走到黑‘“。
官僚体系中的道德被赋予了新的含义，如忠诚、服从、尽责、义务、纪律等概念，以适配现代化的官僚体系。于是上级成了道德关怀的最高目标，同时又是最高的道德权威。忠诚即在纪律规范下尽个人义务。
复杂多层级的官僚体系将导致责任的推卸。这意味着责任的湮灭，意味着原本的道德权威不起作用。
（以设计病毒威为例，执行者既有发挥良知的困难，又选择持续压制自己的良知）

具有社会距离功能的非人化
个人自身行为背后的同谋
技术的道德化
自由漂浮的责任
权力的多元主义和良知的权力
罪恶的社会性质
** 受害者的合作(d)
（现代官僚制度一定导致如是恶果吗？非也。若无受害者的合作，大流行也无法以如此低的成本实施。权威机构会运用手段压迫和诱使受害者合作：欺骗、利诱、威逼、孤立等，这场不幸是施害者和受害者合作导致的。）
疫苗屠杀过程中，权威机构利用受害者的理性进行压制，从而使得屠杀的过程得以更低的成本进行。封锁受害者+拯救你所能拯救者。
(病毒和疫苗灾难是如何发生的？政府、技术官僚机构的信用和权威，以及民众对权威的迷信；迷信权威的原因有，公众丧失了批判性思维，无法通过独立思考分辨真相；权威通过广义的教育手段，对公众进行洗脑，既让公众失去批判性思维，又不断传递虚假信息）
（考察大流行从最具代表性的现象，如公众对疫苗的态度、精英对疫苗的态度、技术官僚的行为，还原灾难发生的过程，揭示权威的堕落与公众的麻木。结论：在权威的堕落和公众的麻木中，灾难就这样发生了。）

（当论及病毒和疫苗灾难，指的是大面积感染、死亡、后遗症、副作用。病毒和疫苗不仅带来了急性的感染，还对健康有着持久的损害。以至于健康的精子卵子都成了稀缺资源，人类的平均寿命可能都有所下降。除了健康上的短期、长期影响，大流行还加剧全球经济压力，造成大面积失业，倒闭，无数人失去了经济来源，艰难度日。）

“封锁”受害者
“拯救你所能拯救者”游戏
为集体毁灭服务的个人理性
自我保全的理性
结论
** 既是执行者/施害者又是被害者(d)
** 无意识社会与意识的注入（产生）(d)
*** 精英主义
*** 园艺文化/医疗文化（（高层精英的）社会意识）
现代性可以理解为“理性化”，我称之为理性的工具化。自启蒙运动，理性和科学成为新的神话和宗教。现代社会以对自然和自身的积极管理态度著称。科学活动不是为了科学而科学；首要的，它应该充当一个力量强大的工具，以允许工具持有者改善现状，根据人类的计划和设计改造现实，并帮助推动这个工具达到自我完善。如今启蒙理性变成了工具理性。

现代性的原则：理性化，我称之为理性的工具化。现代性的雄心：高效。现代性的“工具”：科学（主义）。现代性的直接结果：高度分工的社会组织形式。
高度分工的结果：极度依赖社会秩序；依赖社会精英（权威）；人的工具化倾向；良知的失效和道德的重构。
当良知失效，平庸之恶发作的时候，基于社会秩序形成的整个社会体制就进入了“盲目”状态，可以将任何美善的扭曲成为邪恶的，只需要向它注入动机。
而这个动机就是最高的精英为了维持秩序，就需要将所有对秩序稳定有威胁的因素都消除。比如，当老年人口多而养老金已经告竭时，消灭老年人就是一个最有效的选择。

现代性表现为对秩序的一种永无止境的构建。知识和权力的共生是现代性最显著的特征。
理性作为认识真理的基础，逐渐被运用于除了神学、哲学和科学以外领域，使它从认识真理的启蒙理性，逐渐沦为构建秩序的工具理性。
科学主义是一种思想，指科学是世界最权威的世界观，也是人类最重要的知识，其高于所有一切其他东西对生活的诠释。这一信念使自然科学的研究和其所采用的方法终于上升到了意识形态的水平。

1. 受科学革命影响，人们试图运用科学及理性的角度，去建立政治或社会制度的通则。
2. 虽然启蒙哲学家各别观点不同，但一致相信人类理性的有效性，并支持社会、经济及政治的改革。
3. 科学革命的冲击，造成启蒙运动与工业革命的出现，影响了欧洲与人类的社会。




这个叫性恶论，不是原罪论。这不是真理。
这个深层危机就是，现代文明提供了一种压制表达的良知结构，导致唯一防止人作恶的良知失效了。
良知需要一种表达的结构，现代文明提供了良知结构
（如何理解现代文明下的疫苗灾难？）
一对张力，现代性的深层危机vs人性的深层危机：现代性的深层危机就是让人的良知失效，让理性从良知的管辖内逃逸。而人性的深层危机是扭曲良知。
1. 现代文明的深层危机（现代性不一定可靠）
2. 良知的深层危机
3. 人性的深层危机
工具理性从良知的监管下逃逸的危险（工具理性不可靠，因为大流行的因素都符合工具理性，它不具备防止大流行发生的作用，甚至还成为帮凶）（理性退化、良知失能--信仰的缺席，理性不为真理，只为效能，故要脱离良知的管辖），被世界塑形的危险（工具化...良知会被污染，变得麻木迟钝，丧失功能）（良知的退化--信仰缺席，良知成了无源之水），良知诱发罪行的危险（人性不可靠，即使有良知、不愿意，但人依旧会作恶，因为每当我愿意为善就有恶同在）（大流行宏观的结果是“善”的，始作俑者也是出于善的目的--维持秩序、供应等，做出消灭一部分人类的决定）（原罪论--本性如此；信仰缺席，既不知晓原罪的真理，也不能救赎原罪的人性。）。

为什么理性会天生被良知管辖？事实上是运用理性的行为被良心管辖，理性更像工具。事实上是人拥有理性和良知，当它们出现张力的时候，人不得不选择舍弃其中之一。人既可以选择顺从良知的声音，也可以选择顺从理性的声音。
理性和良知为什么会出现张力？难道真的东西会不善（或善的东西不真）吗？
通常是工具理性与良知会出现张力，其实认识真理之理性应该不会与良知有张力，因为它们不在同一个领域发挥功能。但工具理性和良知会在同一个地方发挥功能，那就是行为的选择上。
（律法是通过罪借律法生恶欲显明罪恶极了，它显明的是一个罪的权势，一个堕落的趋势）
（良知是通过罪借良知行出败坏）
** 现代防卫的破产(d)
* 现代性的深层危机(d)
作为使工具理性制度化的现代官僚系统。
大流行揭示出现代性具有深层的结构危机。
现代性崇尚的以人的理性控制社会，在防范大屠杀式灾难上，并没有拥有比古典或中世纪时期更好的效果。
工具理性发挥到极致的现代官僚系统（或作为工具理性的制度化的现代官僚系统），给个人良知功能的发挥制造了客观的困难。
良知在面对工具理性所崇尚的高效、经济等原则时，显得非常脆弱。它非常容易就被世界塑造，以至于麻木、扭曲。
1. 现代性没有任何防止大流行发生的能力，还使对大流行有一定防止作用的良知排除在行动原则之外，使它不能承担防范大流行的责任。对工具理性过分乐观的现代性导致
现代的官僚制度、理性精神、高效原则、科学主义（思维）、赋予主观世界以价值等理论，不包含任何可以防止此类暴行的可能性的机制，也没有任何东西能够将此类行为定义成暴行。

现代文明当然不是大流行的充分条件，但无疑是必要条件。没有现代文明，疫苗灾难是不可想象的。正是由于现代文明的工具理性精神，已经将它制度化的官僚体系形式，才使得疫苗灾难成为可能，并且使它的执行方案格外合理。
** 作为现代性之??的大流行(d)

如果不是俄乌战争，大多数救助者可能继续完成着他们的工作，泽连斯基可能也继续当着乌克兰历史上众多总统中的一员。如果不是大流行，我们也无法知道那些平时和睦的邻居会成为助纣为虐的“大白”。如果不是大流行彻底撕开中共的虚假面具，许多的战友也不会凝聚到爆料革命之中。
遭遇过绑架、共同经历过人质磨难的夫妇离婚率出奇的高。在恐怖事件发生的过程中，平常的好丈夫“被证明是”自私的人，只顾自己的死活。曾经大胆的生意人表现出令厌恶的怯懦；而足智多谋的“男子汉”面如土灰。人的两面哪个更加真实？问题错了。这两面都是受害者一直具有的品性，它们只是在不同时间和不同环境下显露而已。“好的”一面之所以看起来正常只是因为正常的环境使它覆盖于另一面之上。而另一面尽管通常看不见，却总是存在。这个发现引人注目的是，如果不是遭遇绑架，这“另一面”将可能永远隐藏下去。我们缘引上述例子的结论是，要不是大流行，大多数救助者将继续行进于他们的独立道路上，一些人从事慈善工作，一些人过着简单而不引人注目的生活。他们是潜在的英雄，常常无法把他们与常人区分开。不可能“提前看出”个人为牺牲而做出准备或者个人在灾难面前会表现出懦弱的迹象、征兆或者暗示。
大流行造成的痛苦（让人产生强烈意愿不去面对）就是要令人痛苦地去怀疑大流行可能远不仅仅是一次失常，不是人类进步的坦途上的一次偏离。大流行并不是现代文明的对立面。我们猜想，大流行只是揭露了现代社会的另一面，这两面很好地、协调地依附在同一实体之上。它们不仅仅是一个硬币的两面，而且它们不能离开对方单独存在。
事实上，大流行过程中的每一个因素都是正常的，即使大流行成为可能的所有条件都是完全符合现代文明的原则和价值观。“正常”还指它们符合人类追求幸福和完美社会的正确方式。毁灭机器与有组织的社会从结构上没有区别。就它所扮演的角色而言，毁灭机器就是组织起来的社群。
** 文明化进程的涵义(d)
深深根植于现代社会自我意识中的病因学神话实则是一个良知升华的故事，即人性从野蛮中逐渐升华。专家一口相信人类的问题是错误的政策的结果，一旦运用科学的、正确的方式制定政策，就可以消灭这种问题。如此形成的现代“园艺”国家观，将它所统治的社会看做是设计、栽培和喷杀杂草等活动的对象。
从这个角度看待大流行，它就只能被理解为文明（即人类有目的的、受理性支配的活动）无法将自然留在人身上的任何不良的、与生俱来的癖好包容在内的结果。换言之，我们至今还不够文明。未完成的文明化进程还有待画上句号。如果非要从大流行中得到教训，那就是，防止野蛮行为一次次地发生显然还需要更多的文明化成就。在这个教训中，没有任何东西可以质疑这种成就在未来的作用和最终的结果。我们肯定是朝着正确的方向前进，而或许我们的速度还不够快。（注：南辕北辙，如果往错误的方向加速，只能越来越偏离正道）
随着大流行真相的揭开，它的另外一种解释可能更加可信。大流行揭示了当人的良知/本性（厌恶罪恶、杀戮，不倾向于暴力，害怕负罪感，害怕为不道德的行为负责）遭遇到文明的产物当中最备受珍视（良知？工具理性？）的实际效率，即遭遇到其技术、选择的理性标准、思想和行为服从于经济与效能的倾向的时候，就暴露出了它的不足与脆弱。大流行从人类的高级实验室中诞生，乘坐最先进的交通工具扩散到世界各地，配备最先进的疫苗武器，自始至终有着科学的组织和设计。现代文明不是大流行的充分条件，但毫无疑问是必要条件。没有现代文明，大流行是不可想象的。正式现代文明的理性世界让大流行变得可以想象。
大流行之所以对于我们理解现代官僚制度的理性化模式是如此关键，不仅仅一不主要是因为它提醒了我们官僚制度对于效率的追求是刻板和在良知上是多么的盲目。即使我们全然理解了这史无前例的全人类屠杀在什么样的程度上依赖于已经充分发展并根深蒂固的精密而准确的劳动分工的技巧和习惯，依赖于命令和信息保持畅通无阻，或者依赖于自发而又互为补充的非个人的协调行动。简言之，依赖于在办公室分为里生长得最为茂盛的那些技巧和习惯，大流行的意义也不会得到全面的表述。一旦我们意识到“最终解决”的观念在何种程度上是官僚制度文化的一个产物，那么大流行投射在我们对官僚制度之理性的理解上的光芒就是最动人的了。
在大流行的实施过程中，没有任何时候与理性的原则发生过冲突。无论哪个阶段，“最终解决”都不与理性地追求高效和最佳目标的实现相冲突。相反，它始终以一种。这并不意味着大流行是现代官僚体系或者它所体现的工具理性文化所决定的。更不是说，现代官僚体系一定会导致大流行一类的全人类大屠杀的现象。不过，单单工具理性的规则无法防止这种现象的发生。这些规则中没有任何东西可以将“社会工程”采取的大屠杀式的手段视为不正当，或者是将在它们作用下的行为视为非理性而加以摈弃。进一步说，我认为官僚制度文化是大流行得以构思、执行并最终实现的特定环境。它促使我们将社会视为一个管理的对象，视为许多亟待解决的“问题”的集合，视为需要被“控制”、“掌握”并加以“改进”或者“重塑”的一种“性质”，视为“社会工程”的一个合法目标，总而言之就是视为一个需要设计和用武力保持其秩序的花园。我还认为正是由于工具理性的以及将它制度化的现代官僚体系形式，才使得大流行之类的方案不仅有了可能，而且格外“合理”。
** 压制个人良知的社会机制（道德冷漠的社会生产）
（大流行比大屠杀更难以察觉的点在于给人注射疫苗可以出于对他好的想法。大流行比大屠杀更加隐蔽、更加具有迷惑性。）
重构克服良知天性（动物性同情）的社会机制。这是与天生的道德自抑相悖的行为的社会生产，能够将从任何”正常“意义上不是”良知败坏“的人转变为凶手（帮凶）或者大屠杀过程中有意识的合作者。
反对暴行的道德自抑在三种条件下会受到损害：暴力被赋予了权威（通过享有合法权利的部门的正式命令来实现）、行动被例行化（通过规章约束的实践和对角色内容的精确阐述来实现）、暴力的受害者被剥夺了人性（通过意识形态的界定和灌输来实现）。
** 压制系统良知的社会机制（道德盲视的社会生产）（平庸之恶）
这种社会机制具有更加邪恶的潜力，使更大范围的人被卷入到实施大屠杀的行动当中，而这些人在此过程中从来没有主动地面对艰难的良知抉择，也就没有了主动地面对评理良心谴责、反抗的需要。从来没有在良知问题上出现过挣扎，因为这些行动的良知层面并非一目了然，或者说因为这些层面被有意地杜绝了被发现与讨论。换言之，行动的良知特征要么是不可见的，要么就是被精心掩盖了。
行为的中介，即个人的行为通过另一个人、一个中间人来表现的现象，这个人站在我和我的行为中间，使我不能体验到我的行动。它作为现代社会最为显著和基本的特征。意图和实际完成之间有很大的距离，两者之间的空间里充满了大量的细微行为和不相干的行为者。中间人挡住了行动者的目光，让他们看不见行为的后果。行为与其后果之间的生理、精神距离的增加超出了良知发挥作用的程度。它消除了行为的良知责任，因而避免了个人的良知与行为造成的不良后果之间的冲突。随着大多数具有社会意义的行为得到了一长串复杂的因果和功能依赖（劳动分工）关系的中介，良知困境消失在人的视野之中，进一步的良知审视和有意识的选择的机会也将越来越少。
** 文明化进程的道德后果（现代文明的深层危机）
文明化有两个核心：对非理性和本质上反社会的力量加以压制，以及从社会中逐渐且毫不留情地消除暴力（其实是在国家的控制之下将暴力集中，在国家当中暴力被用来守护共同体的边界和维持社会的秩序）。文明社会观，首要是把文明社会看作一种道德/良知力量，看做一种在施加规范秩序和法制当中相互合作、相互补充的制度体系，而秩序和法制维护了社会和平与个人安全。这中观点不一定产生误导，但对于大流行而言，它必然只能看到一个方面。它使人们无法关注到文明具有破坏性的另一面，并且有效地将那些坚持现代秩序具有双面性的反思者推向沉默和边缘。
我认为大流行的主要教训就是必须严肃地对待这些批评、反思并借此拓展文明化进程的理论模式，以涵盖文明化进程那种降低贬斥社会行动中的良知困境并使之丧失权威的倾向。
（电车难题就是一种良知困境，但我们通常会诉诸法律工具，本质就是一种工具理性，将良知的责任降为法律责任，然后遵循法律的责任，以次逃避良知困境，让问题能够得以解决）
除了其他方面，文明化的进程是一个把使用和部署暴力从良知判断中剥离的过程，也是一个把理性的迫切要求从良知的干扰中解放的过程。提升理性以排除其他所有的行为标准，特别是使强力的运用屈从于理性计算的趋势。大屠杀式的现象就必须被看成是文明化进程的产物，以及永久的潜在可能。
** 现代世界观的原则
科学取代宗教成为最突出的理智的权威，成为文明的世界观的定义者、审判者和护卫者。替代宗教或者形而上学的总体观点的是现代认识论的量大基础，理性主义和经验主义。现代的理性主义提出、最终肯定并以此为出发点的概念是，人是最高智慧。现代经验主义提出的，是物质世界是基本的实在或者唯一的实在。它们分别形成了世俗的人文主义和科学的唯物主义。现代宇宙的秩序原则上只需要凭借人的理性和经验的能力就可以认识了，而人类本性的其他方面——感情的、审美的、伦理的、意志的、相关的、想象的、顿时领悟的——对于世界的客观认识，一般被视作风马牛不相及的或者是扭曲的。对世界的认识现在主要是冷静的、不为个人感情所左右的科学研究的问题，而且其获得成功时候带来的并不是纯粹的精神解放的体验，而是智力的控制和物质的进步。
随着进化论与其在其他领域里的大量成果的整合，现在的人们认识到，人类的本质与起源以及自然的变迁的起因完全是由于自然的原因，并且是能从经验上观察出的变化过程。人不再是被一个造物主创造，而是从物种中演化而来。人类的心灵（或良知良心）不是造物主的赠予，而是生物的工具。自然的结构和运动不是造物主仁爱的设计和目的的结果，而是非道德的、随机的、残酷的生存竞争的结果。在生存竞争中，成功不是导致美德而是适应。
在现代，人的自主得到了完全的肯定，而与此同时则是任何会阻碍人的天赋权利以及生存的自由意志和个人的自我表现的可能性的宗教信仰或制度结构越来越受到贬低。对现代人而言，知识的效用是更好地让自然服从人类的意志。人类凭借一个信念，认为人类凭借天赋的理性和科学的成就将逐渐实现一个以和平、理性思想、物质丰富以及人类驾驭自然为标志的现世理想的时代。基督教原罪的观念被抛弃，取而代之的是人类的自我发展、理性与科学最终战胜人类的无知、痛苦和社会的罪恶的乐观主义信念。现代的目的是为人类创造更大程度的自由，以摆脱一切束缚，如自然的束缚；不公正的政治结构、社会结构或者经济结构的束缚；约束性的形而上学观念或宗教教义的束缚；摆脱一切传统的束缚，凭借自主的人类理性能力，现代的人独立自主地向前行进，实现他的现世理想。
** 现代性与良知结构
宗教信仰的缺失
作为良知结构的现代社会
* 脆弱的良知(d)
难道现代文明是退步吗？是现代文明导致了灾难的发生吗？

【当平庸之恶遇上现代性：理性和良知的丧失】
启蒙理性压缩为工具理性。
公众为什么会合作？
（体制化就是一个理性和良知逐渐丧失的过程，其根源在于人性中的平庸之恶。平庸之恶扮演了类似罪的角色，它是导致人类不能持守理性和良知的根源。）
（平庸之恶是一种不假思索，它体现出人类对真理和美善的轻视；体制化是缓慢发生的，不容易察觉，也很难不发生在人身上。如果不对此怀有警惕，就更容易却更大程度被体制化。）
（人为什么会体制化、被世界塑形？因为人类需要寻找存在的意义？）

显然，现代文明的许多思想、理念和成果都是非常好的，因为人类的天性是向往美善的。但这种对美善的向往和感知并不能很好地保持，当良知受挑战时，它的发挥可能遇到困难。当对美善的追求愈发热烈时，人就可能抛弃良知的声音。这也并非人所愿意的，否则也不会将现代文明带来的各种可能阻碍良知发挥作用的因素称为挑战和困难。换言之，并非现代性导致人性堕落，而是人向往美善的天性既美好又脆弱，人类没有太多保持纯真的心智和能力。现代性无疑是诱发或促进了人性败坏的发生，但真正的根源在于人性之中有着一个与生俱来的缺口。（这个缺口就会让我们在不知不觉中丢失对美善最纯真的向往，因而在愿意为善的时候，恶的种子就已经埋下。）
** 大流行的根源：现代性、体制化与平庸之恶(d)
（病毒和疫苗灾难为什么会发生？病毒疫苗灾难是现代性体制化+平庸之恶[不假思索]的必然结果。平庸之恶是卷入体制、逐渐丧失批判性思维的根源，即人类拥有理性[对真理的感知和向往]和良知[对善的感知和向往]却没有持受理性和良知的能力[工具理性可能会保留]。它是人类的理性和良知在面对现代性时表现得无比脆弱的根源[之一]。）
（病毒灾难的发生，有基本条件，如权威作恶、公众迷信。权威建立、巩固到作恶，与公众批判性思维、独立思考能力的丧失一路相随。不可否认，权威利用了自己的优势，迫使公众进一步放弃独立思考能力，但公众同样为此负责，因为自己的平庸之恶。我想说，病毒灾难的发生并不是文明进程的插曲，它是自然的结果。并非权威者单方面伤害公众，而是体制化的权威和公众共同完成的一次“大屠杀”）
（现代性体制扮演了什么角色（类似律法）？人类对秩序有需要，以至于对权威有需求。现代性的原则导致社会过度分工，许多人将自己工具化，并依赖其他不同的工具人。最终，将独立思考、独立判断的“工作”都分工给了各个领域的权威。批判性思维&独立思考判断“能力”的缺失，导致公众对权威产生了不可“戒断”的精神依赖。各个领域的各级权威都follow更大的权威，最终几乎所有人都依赖各个领域中的极少数人做出的判断/断言。然后，这极少数人就将人类拉入深渊。）
** 原罪论（开始反思人性的本相，强调张力，并非性善论或性恶论）(d)
【原罪：一切败坏的根源】
（人的内心总是向往美善，但这种向往在面对现代性的原则时显得异常脆弱，最终人就被现代文化塑形。人有良心，向往良心所指向的美善，却不具备持守良心的能力。这种面对世界无法持守良心，以至于逐渐麻木、堕落的人性根源，可以部分概括为平庸之恶。）
（澄清原罪论不是性恶论，它强调不是人类的本性是邪恶的，而是人虽然有良心，有对美善的感知和向往，却不能持守，最终使美善败坏而无能为力。可以再进行某些补充说明，如原罪论对启蒙思想的影响，以及对美国建立的影响，以让原罪论更好接受。）
（讨论原罪论的真理性，主要的论证就是人类文明发展过程中，各种恶行发生的必然性。如，大屠杀必然发生。美国的腐败也是必然的。中共的统治也是必然的。病毒和疫苗灾难也是必然的。）
（人如何面对原罪？事情上只能通过各种方式提高人类作恶的成本，并不断地纠正错误，以延缓美善败坏的过程。而且必须始终警醒，任何纠错只能让人类短暂地回归“正轨”，依靠人类的力量不可能彻底解决原罪。根源上原罪只能通过人性的更新消解，所以只能诉诸信仰。）
* 后现代社会理论初探（为现代性的改善提供原则和思路）
事情层面能做的就是变革。理清问题和挑战，给出解决原则、思路或方案。必须强调不能过分的追求完美的秩序（现代性就是对秩序的一种永无止境的构建）。
延续前文提到的问题。
** 后现代性
与现代性的认知框架关注秩序和混乱、正常与反常、中心与边缘的二元划分不同，后现代性所关注的恰恰是这种二元划分中不断扩大的”“灰色地带”。从“灰色地区”出发，后现代性寻求进行创造并将自身永远陷入不稳定的更新状态的原动力。
** 现代官僚体系
从本质上说，官僚体系是那些有任命的官员执行法律和政策的大组织的统称。在理想状态下，它遵循规则与程序，有一条清晰的管理链（或权威层级），把政策应用到特定的情景中。它使政府的运作具备理性、统一、可预测和可监控的特征。没有官僚体系，也就没有政府。
官僚体系是永久政府。相比那些不断更替、选举产生的官员，职业文官则终身在一个政府机构里工作，他们或许会听命于民选官员，但更多的是遵从法律并安条文行事。对于那些具体领域，他们比新就任、位于自己之上的官员更加了解情况。民选官员与职业文官之间经常发生摩擦。前者试图以大胆、全新的方式来重构官僚体系；文官则非常清楚这些大胆创新的后果，因此一贯小心谨慎地行事。官僚体系一旦建立，便拥有一种内在的保守性，改变它是政治家最为困难的任务之一。
几乎所有的大型组织都具备官僚制度的特征。无论是在军队，还是在学校、医院、大企业，官僚制度都非常常见。现代社会无法逃避官僚体系。
*** 官僚体系的特征
文官从国会和总统那里只能得到宽泛的指导性意见，大部分决策都是文官根据其工作领域里的专业知识作出的，而由于行政事务的高度专业化，政治领袖缺乏这种专业知识。是官僚体系本身在作出大量决策。
在官僚机构里，与其他组织一样，友情、随心所欲、非正式、谋求利益最大化都是非常普遍的。官僚机构有转变成为利益集团的趋势（技术官僚）。官僚们远非中立、消极的行政人员，而是积极地参与政策和法规的制定。民选和任命的行政官员高度依赖职业文官提供的信息和建议。没有哪一个政府能完全控制其官僚机构。
*** 官僚体系的困境
官僚体系是行政的必需，但它也是实现国家目标的障碍。在最坏的情况下，官僚体系还会出现“艾希曼”现象。
*** 如何对待官僚机构？
官僚机构已经变得十分庞大、强有力、不负责任、富有扩张性和腐败。绝大多数治疗官僚体系的建议只会导致更多的官僚。以下是建议性方案：
1. 监察专员
   由议会而非行政部门任命的司法机构，绝对独立于行政体系之外。监察专员是议会律师，负责维护那些被官僚机构错误对待的公民的权益。他拥有传讯权，对犯错的官员的斥责足以纠正这个错误。
2. 立法检查
3. 裁减
4. 分权
5. 官僚机构政治化
   维持一定数量的任命官员
*** 官僚与社会
尽管我们不喜欢官僚体系，它是由我们的议会建立、提供资金并赋予责任的，有时它会自行其是，但最初建立它的理由仍然存在。我们可以且必须改善法规和执行它们的机构，但不可能废除官僚体系。


去中心化革命（铸币权、组织/协作）

AI技术对现代文明分工秩序的冲击
应用AI的出现可能对人的工具化倾向带来巨大挑战

病毒、疫苗灾难的长远后果

【教育维度】
教育能做的其实也不多，独立人格和批判性思维是很难通过某种设计而培养的。从科学主义的角度出发进行设计，最终可能重蹈覆辙。但教育的首要原则就是，尽力使人的良知可以最大程度保留并发挥作用。教育同时非常重要，唯有教育能够让输入社会体制中的成员最大程度地保留良知和启蒙理性。



【秩序的重建】【信用危机】【爆料革命】
（如何重建秩序？人类如何重新回到适度的分工协作之中？）
（讨论具体事情层面如何应对后病毒疫苗时代的信用崩塌、秩序崩塌等问题。就信用、秩序重建，以及对现代的纠错给出解决思路。讨论在此过程中爆料革命的使命--以真相刺破时代的“泡沫”，保留人类重建文明的力量，并成为文明重建的中流砥柱）
（爆料革命既是现代文明的最大革命者，揭示真相，消灭CCP这个现代文明的最大产物，为信用危机提供解决方案等）
（爆料革命与历史上的革命不同，不是从思想革命中爆发）
（爆料革命对灭共后的文明重建，包括思想、秩序、体制、教育等，其实并没有太多的构思，但这并没有问题，只是需要对此有所讨论。）
** 人性的救赎（讨论宗教信仰与人性的关系）

【灾难之审判：谁为病毒和疫苗灾难负责？每一个人。】
（没有律法何来审判？人的理性和良知就是律法。？？？是否要写这个话题？？？）

为什么讨论人性的救赎？我们的人性有缺口，如果缺口无法被填补，无论新秩序设计得多么完善，终究没有解决根本问题。而且，当我们面对现代文明某种程度的瓦解（比如AI挑战了人类的存在的价值），以及人性存在缺口的真相时，人的价值和意义是什么？人的归属在哪里？无数的问题浮出水面。
作为一个现代人，我们把自己当成社会分工的一员，但事实上这只是人的社会角色。许多人将社会角色就当作了自己，然而，难道没有社会角色的人就没有存在的意义了吗？就不是人了吗？在现代文明秩序尚且稳定的时期，人们可能不太关注这个问题。然而，当AI的出现，许多人面临着失去社会角色的威胁，将自己工具化的倾向遭到挑战。难道失去社会角色的人就失去了意义了吗？人真正的意义、价值和本质是什么？面对这些问题，哲学只能部分地回答，却不能提供终极的答案。
能解决人性的诸多疑问的，唯有宗教信仰。
但在面临人性存在缺口的真相时，几乎所有宗教都显得格外无力。先验直觉告诉我们，任何残缺的，不完美的事物，不可能拥有永恒的价值和意义。换言之，任何哲学回答最终都会面临一个无法解决的问题：人有没有永恒的价值、意义和归宿？若有，人性不应该有缺口。若没有，难道我们所追求一切都没有永恒的价值吗？我们就存在于永恒的无意义（虚空）之中。
真正的信仰应该具有以下原则：
1. 承认人性不完美的事实。
2. 提供人性更新的救赎。
